apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name  : xenn-cluster
  region: eu-north-1

nodeGroups:
  - name             : worker
    instanceType     : t3.micro
    desiredCapacity  : 3
    privateNetworking: true                         # Use Private Subnets

