apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deploy-autoscaling
  labels:
    app: my-k8s-deploy
spec:
  selector:
    matchLabels:
      project: kgb        #Service will look for these PODs labels!!!
  template:
    metadata:
      labels:
        project: kgb
    spec:
      containers:
        - name: kgb-web
          image: micro1985/myk8sap:latest
          ports:
            - containerPort: 80   # port on POD

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaling
  labels:
    env   : prod
    owner : xenn
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name: my-web-deploy-autoscaling
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-autoscaling-pod-service
  labels:
    env   : prod
    owner : xenn
spec:
  type: LoadBalancer
  selector:
    project: kgb         #selecting PODs with those labels - kgb
  ports:
    - name       : kgb-app-listener
      protocol   : TCP
      port       : 80 # Port on LoadBalancer
      targetPort : 80 #Port on POD

