apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deploy
  labels:
    app: my-k8s-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      project: fbi        #Service will look for these PODs labels!!!
  template:
    metadata:
      labels:
        project: fbi
    spec:
      containers:
        - name: fbi-web
          image: micro1985/myk8sap:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-single-pod-service
  labels:
    env   : prod
    owner : xenn
spec:
  selector:
    project: fbi         #selecting PODs with those labels - fbi
  ports:
    - name       : app-listener
      protocol   : TCP
      port       : 80 # Port on LoadBalancer
      targetPort : 80 #Port on POD
  type: LoadBalancer
